behaviors:
  RunAway:
    trainer_type: ppo
    hyperparameters:
      batch_size: 8192
      buffer_size: 16384
      learning_rate: 0.001
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 3000000
    time_horizon: 64
    summary_freq: 50000
environment_parameters:
  movementSpeed:
    curriculum:
      - name: prey-intro
        completion_criteria:
          measure: progress
          behavior: RunAway
          signal_smoothing: true
          min_lesson_length: 100
        value: 1.2
  rotationSpeed:
    curriculum:
      - name: prey-intro
        completion_criteria:
          measure: progress
          behavior: RunAway
          signal_smoothing: true
          min_lesson_length: 100
        value: 100
  randomRespawnTarget:
    curriculum:
      - name: Prey-DynamicRespawn
        completion_criteria:
          measure: progress
          behavior: RunAway
          signal_smoothing: true
          min_lesson_length: 100
        value: 1.0
