behaviors:
  Shooter:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 8196
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory:
        memory_size: 256
        sequence_length: 64
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4
      # gail:
      #   strength: 0.01
      #   gamma: 0.99
      #   encoding_size: 128
      #   demo_path: Assets/Demonstrations/ShooterDemoElo38.demo
      #   learning_rate: 3.0e-4
      #   use_actions: true
      #   use_vail: false
    self_play:
      save_steps: 100000
      team_change: 500000
      swap_steps: 50000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 100
    summary_freq: 50000
    threaded: true
environment_parameters:
  initialAmmo:
    curriculum:
      - name: intro-Shooters
        completion_criteria:
          measure: progress
          behavior: Shooter
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.01
        value: 100.0
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: Shooter
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
        value: 100.0
      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: Shooter
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.4
        value: 50.0
      - name: Master
        value: 30.0